### ISSUE TITLE
Run issues

### ISSUE THREAD

**Issue by dagisus** [xadrijo/compara-test#1]
Hello @xadrijo, 

We saw some issues running your project, is there a possibility you could fix them???

- Building your project using the README instructions, there is a small issue on your build command missing the context param
- The running project responds with a 403 

We look forward to your fixes and further conversations 👍

**Comment by jorgejimenez36** [comment]
Hello @dagisus,

Issues are already solved. 

- I forgot to add a point at the end of the first docker command. 

- And I removed the src in the second command to fix the 403 forbidden error.

It is working now. I'm so sorry for those issues.

**Comment by xadrijo** [comment]
Hello @dagisus,

Issues are already solved. 

- I forgot to add a point at the end of the first docker command. 

- And I removed the src in the second command to fix the 403 forbidden error.

It is working now. I'm so sorry for those issues.
